/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

import "sst"

declare module "sst" {
  export interface Resource {
    Database: {
      database: string
      host: string
      password: string
      port: number
      type: "sst.mysql.Database"
      username: string
    }
  }
}
export {}
