id = "openqcode"
name = "OpenQCode"
description = "The open source coding agent."
version = "1.15.11"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/openqcode"

[agent_servers.openqcode]
name = "OpenQCode"
icon = "./icons/openqcode.svg"

[agent_servers.openqcode.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/openqcode/releases/download/v1.15.11/openqcode-darwin-arm64.zip"
cmd = "./openqcode"
args = ["acp"]

[agent_servers.openqcode.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/openqcode/releases/download/v1.15.11/openqcode-darwin-x64.zip"
cmd = "./openqcode"
args = ["acp"]

[agent_servers.openqcode.targets.linux-aarch64]
archive = "https://github.com/anomalyco/openqcode/releases/download/v1.15.11/openqcode-linux-arm64.tar.gz"
cmd = "./openqcode"
args = ["acp"]

[agent_servers.openqcode.targets.linux-x86_64]
archive = "https://github.com/anomalyco/openqcode/releases/download/v1.15.11/openqcode-linux-x64.tar.gz"
cmd = "./openqcode"
args = ["acp"]

[agent_servers.openqcode.targets.windows-x86_64]
archive = "https://github.com/anomalyco/openqcode/releases/download/v1.15.11/openqcode-windows-x64.zip"
cmd = "./openqcode.exe"
args = ["acp"]
